export interface OrderHistory {
    id: number,
    createdByStaff: string,
    createdByUser: number,
    ip: string,
    createdAt: number,
    orderMethod: string,
    paymentMethod: string,
    payOnSystem: string,
    transactionId: string,
    shipAddress: string,
    shipCountry: 'US',
    shipState: string,
    shipCity: string,
    shipPhone: string,
    shipEmail: string,
    shipFirstName: string,
    shipLastName: string,
    shipZipCode: string,
    billingAddress: string,
    billingCountry: 'US',
    billingState: string,
    billingCity: string,
    billingPhone: string,
    billingEmail: string,
    billingFirstName: string,
    billingLastName: string,
    billingZipCode: string,
    shippingGroupId: number,
    tax: number,
    taxFee: number,
    shippingFee: number,
    subTotal: number,
    grandTotal: number,
    promoCode: string,
    discount: number,
    surcharge: number,
    status: string,
    note: string,
    userNote: string,
    shippingFeeCalculatedBy: string,
}

export interface CartItem {
    skuId: number,
    title: string,
    type?: string,
    price: number,
    quantity: number,
    weight: number,
    namePromotion: string,
    qtyProductOfPromotion: number,
}

export type Weight = {
    id: number,
    name: string,
    zoneFrom: number,
    zoneTo: number,
    fee: number,
}

export type Discount = {
    id: number,
    name: string,
    status: string,
    startAt: Date,
    endAt: Date,
    discountBasedOn: string,
    discountValue: number,
    minSubtotal: number,
}

export type Promotion = {
    id: string,
    name: string,
    skuIdIn: number,
    skuNameIn: string,
    skuIdOut: number,
    skuNameOut: string,
    skuWeightOut: number,
    status: string,
    quantityIn: number,
    quantityOutMax: number,
    startAt: Date,
    endArt: Date,      
}
